apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: addtocart-poc
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
  - accessStrategies:
    - config: {}
      handler: noop
    methods:
    - POST
    - GET
    - PATCH
    - DELETE
    - PUT
    - HEAD
    path: /.*
  service:
    host: addtocart-poc.#{POD_SS_DOMAIN}#-ao.tatadigital.com
    name: addtocart-poc
    port: 80
